services:
  praulitis:
    build: .
    container_name: praulitis_app
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Europe/Riga
      DATABASE_PATH: /app/data/praulitis.db
      UPLOAD_PATH: /app/app/static/uploads
      AWS_S3_BUCKET: praulits-media
      AWS_S3_REGION: us-east-1
    volumes:
      - ./data:/app/data
      - ./app/static/uploads:/app/app/static/uploads
      - /home/udzerins/.aws:/root/.aws:ro
    ports:
      - "5002:5002"
